[application]

# App (Project) Name
name = "johntest-fs"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
#out_dir = "dist"
out_dir = "docs"

# resource (assets) file folder
asset_dir = "assets"

[web.app]
# Added this to deploy to github docs
# base_path = "docs"

# HTML title tag content
title = "johntest-fs"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
